### ISSUE TITLE
GUI v API export/import

### ISSUE THREAD

**Issue by brsolomon-deloitte** [corelight/ecs-dashboards#3]
README should specify whether these ndjson files were generated using a GUI or API export, [since there is an incompatibility between the two](https://discuss.elastic.co/t/not-able-to-view-saved-object-after-importing-via-api/209666/4). It could also state what specific version of Kibana they were exported from given the [compatibility specifications](https://www.elastic.co/guide/en/kibana/current/saved-objects-api-import.html#_compatibility_across_versions_2).

**Comment by hunter32me** [comment]
The v25 have been published to github

**Comment by brsolomon-deloitte** [comment]
@hunter32me The core of this issue was around the difference between ndjson files generated by GUI or API. It looks like there is still only one ndjson for v25, presumably the version generated by API.

**Comment by hunter32me** [comment]
The NDJSON file is GUI generated right now, this one fixes the problem for loading in version lower then 7.16
